### ISSUE TITLE
Sample 启动崩溃

### ISSUE THREAD

**Issue by mikelhm** [iqiyi/Qigsaw#11]
java.lang.RuntimeException: Unable to get provider com.iqiyi.qigsaw.sample.java.JavaContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.iqiyi.qigsaw.sample.java.JavaContentProvider" on path: DexPathList[[zip file "/data/app/com.iqiyi.qigsaw.sample-u8wRcwFsQ0wfnQl1TzqxGA==/base.apk"],nativeLibraryDirectories=[/data/app/com.iqiyi.qigsaw.sample-u8wRcwFsQ0wfnQl1TzqxGA==/lib/arm64, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6717)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6215)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6132)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:7022)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.iqiyi.qigsaw.sample.java.JavaContentProvider" on path: DexPathList[[zip file "/data/app/com.iqiyi.qigsaw.sample-u8wRcwFsQ0wfnQl1TzqxGA==/base.apk"],nativeLibraryDirectories=[/data/app/com.iqiyi.qigsaw.sample-u8wRcwFsQ0wfnQl1TzqxGA==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6702)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6215)?
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6132)?
        at android.app.ActivityThread.-wrap1(Unknown Source:0)?
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)?
        at android.os.Handler.dispatchMessage(Handler.java:106)?
        at android.os.Looper.loop(Looper.java:197)?
        at android.app.ActivityThread.main(ActivityThread.java:7022)?
        at java.lang.reflect.Method.invoke(Native Method)?
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)?
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)?

**Comment by kissonchan** [comment]
请用qigsaw提供的命令编译

**Comment by mikelhm** [comment]
请问下是哪个命令呢   readMe文件 没有说用具体的命令编译

**Comment by kissonchan** [comment]
> 的

readMe 里面有，qigsawAssembleDebug命令
