### ISSUE TITLE
Qigsaw兼容Gradle 插件 4.1.0吗？

### ISSUE THREAD

**Issue by GlimmerYang** [iqiyi/Qigsaw#69]
最近版本升级到gradle 4.1.0：classpath 'com.android.tools.build:gradle:4.1.0'
出现如下问题：
Caused by: org.gradle.api.GradleException: com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest_Decorated
	at com.iqiyi.qigsaw.buildtool.gradle.internal.tool.AGPCompat.getBundleManifestDirCompat(AGPCompat.groovy:106)
	at com.iqiyi.qigsaw.buildtool.gradle.internal.tool.AGPCompat$getBundleManifestDirCompat$8.call(Unknown Source)
	at com.iqiyi.qigsaw.buildtool.gradle.QigsawAppBasePlugin$_apply_closure1$_closure5.doCall(QigsawAppBasePlugin.groovy:110)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:94)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:163)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:198)
	at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
	at com.iqiyi.qigsaw.buildtool.gradle.QigsawAppBasePlugin$_apply_closure1.doCall(QigsawAppBasePlugin.groovy:92)

**Comment by yizems** [comment]
see 
https://github.com/yizems/QigsawDemo
你这个应该是 第一个问题造成的

**Comment by yizems** [comment]
https://github.com/yizems/QigsawDemo2
